### ISSUE TITLE
可以查成績的主機還有這幾台

### ISSUE THREAD

**Issue by imgarylai** [ctxhou/NCKU-GPA-calculator#1]
This commit: 379bbabba1f5d41ee52ba38499644092d798a2cb

http://140.116.165.71:8888/ncku/qrys02.asp
http://140.116.165.72:8888/ncku/qrys02.asp
http://140.116.165.73:8888/ncku/qrys02.asp

**Comment by imgarylai** [comment]
#2

**Comment by ctxhou** [comment]
merge
