### ISSUE TITLE
學校好像要改換算的標準

### ISSUE THREAD

**Issue by d4n1elchen** [ctxhou/NCKU-GPA-calculator#5]
參考104/5/28 103年第二次教務會議 國立成功大學學生成績處理作業要點 
會議記錄: http://acad.ncku.edu.tw/ezfiles/12/1012/img/2259/188390409.pdf

二、 本校自 104 學年度起，學生學期成績以百分制與等第制並列，授課教師成
績以百分制輸入，由系統依「等第制與百分制單科成績對照表」(附表一)
自動轉換等第成績。

附表一
成功大學等第制與百分制單科成績對照表（附表一）
| Grade | 分數區間 | Point |
| -------- | ----------- | ------- |
| A+ | 90~100 | 4.3 |
| A | 85~89 | 4.0 |
| A- | 80~84 | 3.7 |
| B+ | 77~79 | 3.3 |
| B | 73~76 | 3.0 |
| B- | 70~72 | 2.7 |
| C+ | 67~69 | 2.3 |
| C | 63~66 | 2.0 |
| C- | 60~62 | 1.7 |
| F | 59以下 | 0 |

另外看敘述好像之後會加入自動換算，然後我想順便問問學長sitw的事，可以交換個facebook嗎?
這是我的FB: https://www.facebook.com/danielchen.dc

**Comment by ctxhou** [comment]
感謝你的回報！

**Comment by ctxhou** [comment]
#6 fixed
